server:
  port: 7050
spring:
  application:
    name: funhub
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/funhub?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
inmbank:
  funhub:
    image-folder: ${RESOURCE_FOLDER:folder}
    host: ${EMAIL_HOST:host}
    sender: ${EMAIL_SENDER:sender}
    cron: ${NOTIFICATION_DATE_TIME:0 0 8 * * *}
